services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\Eshop\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry

  OxidEsales\Eshop\Core\Request:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getRequest' ]

  HkReuter\ModuleTest\Service\:
    resource: 'src/Service/*'
    public: true

  HkReuter\ModuleTest\Subscriber\BeforeModelUpdate:
    class: HkReuter\ModuleTest\Subscriber\BeforeModelUpdate
    tags: [ 'kernel.event_subscriber' ]